### PR TITLE
v2.6 Key

### PR DESCRIPTION
**Pull request by hashblen**

### CODE REVIEW

**Review by tamilpp25 — APPROVED** [review]

**Comment by SSSLiurong** [comment]
how to get version keys by using these codes? base-64?

**Comment by hashblen** [comment]
> how to get version keys by using these codes? base-64?

If you are talking about the keys mapping the Dispatch Keys in the json. I suggest you look here https://github.com/tamilpp25/Iridium-SR/blob/main/sniffer.go#L198
If you don't see it, I can explain how to get it directly from the key.

If you're talking about anything else, I don't know what you mean

**Comment by SSSLiurong** [comment]
> > how to get version keys by using these codes? base-64?
> 
> If you are talking about the keys mapping the Dispatch Keys in the json. I suggest you look here https://github.com/tamilpp25/Iridium-SR/blob/main/sniffer.go#L198 If you don't see it, I can explain how to get it directly from the key.
> 
> If you're talking about anything else, I don't know what you mean

I mean, how to get GetVideoVersionKeyScRsp.json from ".Iridium-SR-main/data/Keys.json"，which update 2.6Keys.

**Comment by hashblen** [comment]
> > > how to get version keys by using these codes? base-64?
> > 
> > If you are talking about the keys mapping the Dispatch Keys in the json. I suggest you look here https://github.com/tamilpp25/Iridium-SR/blob/main/sniffer.go#L198 If you don't see it, I can explain how to get it directly from the key.
> > 
> > If you're talking about anything else, I don't know what you mean
> 
> I mean, how to get GetVideoVersionKeyScRsp.json from ".Iridium-SR-main/data/Keys.json"，which update 2.6Keys.

This has nothing to do with it. `Keys.json` is the list of dispatch keys to handle the encryption of the first packets in the login sequence.

**Pull request merged**
